// Generated by rstantools.  Do not edit by hand.

/*
    HBomics is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HBomics is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with HBomics.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_HBomics_pal_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 73> locations_array__ =
  {" (found before start of program)",
  " (in 'HBomics_pal', line 60, column 2 to column 40)",
  " (in 'HBomics_pal', line 61, column 2 to column 40)",
  " (in 'HBomics_pal', line 62, column 2 to column 40)",
  " (in 'HBomics_pal', line 63, column 2 to column 41)",
  " (in 'HBomics_pal', line 66, column 2 to column 36)",
  " (in 'HBomics_pal', line 104, column 2 to column 20)",
  " (in 'HBomics_pal', line 105, column 2 to column 22)",
  " (in 'HBomics_pal', line 106, column 2 to column 27)",
  " (in 'HBomics_pal', line 107, column 2 to column 22)",
  " (in 'HBomics_pal', line 68, column 4 to column 36)",
  " (in 'HBomics_pal', line 67, column 18 to line 69, column 3)",
  " (in 'HBomics_pal', line 67, column 2 to line 69, column 3)",
  " (in 'HBomics_pal', line 110, column 4 to column 37)",
  " (in 'HBomics_pal', line 111, column 4 to column 42)",
  " (in 'HBomics_pal', line 113, column 4 to column 54)",
  " (in 'HBomics_pal', line 116, column 4 to column 41)",
  " (in 'HBomics_pal', line 119, column 4 to line 120, column 70)",
  " (in 'HBomics_pal', line 122, column 4 to column 58)",
  " (in 'HBomics_pal', line 109, column 18 to line 123, column 3)",
  " (in 'HBomics_pal', line 109, column 2 to line 123, column 3)",
  " (in 'HBomics_pal', line 74, column 2 to column 27)",
  " (in 'HBomics_pal', line 76, column 9 to column 10)",
  " (in 'HBomics_pal', line 76, column 2 to column 14)",
  " (in 'HBomics_pal', line 77, column 9 to column 10)",
  " (in 'HBomics_pal', line 77, column 2 to column 20)",
  " (in 'HBomics_pal', line 80, column 4 to column 34)",
  " (in 'HBomics_pal', line 83, column 4 to column 41)",
  " (in 'HBomics_pal', line 86, column 4 to column 66)",
  " (in 'HBomics_pal', line 78, column 19 to line 87, column 3)",
  " (in 'HBomics_pal', line 78, column 2 to line 87, column 3)",
  " (in 'HBomics_pal', line 91, column 4 to column 31)",
  " (in 'HBomics_pal', line 93, column 4 to column 90)",
  " (in 'HBomics_pal', line 94, column 4 to column 48)",
  " (in 'HBomics_pal', line 98, column 4 to column 52)",
  " (in 'HBomics_pal', line 99, column 4 to column 36)",
  " (in 'HBomics_pal', line 89, column 17 to line 100, column 3)",
  " (in 'HBomics_pal', line 89, column 2 to line 100, column 3)",
  " (in 'HBomics_pal', line 37, column 2 to column 17)",
  " (in 'HBomics_pal', line 38, column 2 to column 17)",
  " (in 'HBomics_pal', line 39, column 2 to column 17)",
  " (in 'HBomics_pal', line 41, column 8 to column 9)",
  " (in 'HBomics_pal', line 41, column 2 to column 44)",
  " (in 'HBomics_pal', line 42, column 8 to column 9)",
  " (in 'HBomics_pal', line 42, column 2 to column 45)",
  " (in 'HBomics_pal', line 43, column 8 to column 9)",
  " (in 'HBomics_pal', line 43, column 2 to column 17)",
  " (in 'HBomics_pal', line 45, column 8 to column 9)",
  " (in 'HBomics_pal', line 45, column 2 to column 17)",
  " (in 'HBomics_pal', line 46, column 8 to column 9)",
  " (in 'HBomics_pal', line 46, column 2 to column 17)",
  " (in 'HBomics_pal', line 47, column 8 to column 9)",
  " (in 'HBomics_pal', line 47, column 2 to column 36)",
  " (in 'HBomics_pal', line 49, column 8 to column 9)",
  " (in 'HBomics_pal', line 49, column 2 to column 29)",
  " (in 'HBomics_pal', line 50, column 8 to column 9)",
  " (in 'HBomics_pal', line 50, column 2 to column 29)",
  " (in 'HBomics_pal', line 51, column 2 to column 23)",
  " (in 'HBomics_pal', line 53, column 2 to column 29)",
  " (in 'HBomics_pal', line 54, column 2 to column 23)",
  " (in 'HBomics_pal', line 55, column 2 to column 18)",
  " (in 'HBomics_pal', line 56, column 2 to column 17)",
  " (in 'HBomics_pal', line 60, column 35 to column 36)",
  " (in 'HBomics_pal', line 61, column 35 to column 36)",
  " (in 'HBomics_pal', line 62, column 35 to column 36)",
  " (in 'HBomics_pal', line 63, column 35 to column 36)",
  " (in 'HBomics_pal', line 66, column 27 to column 28)",
  " (in 'HBomics_pal', line 104, column 9 to column 10)",
  " (in 'HBomics_pal', line 105, column 9 to column 10)",
  " (in 'HBomics_pal', line 106, column 9 to column 10)",
  " (in 'HBomics_pal', line 107, column 9 to column 10)",
  " (in 'HBomics_pal', line 30, column 4 to column 49)",
  " (in 'HBomics_pal', line 29, column 29 to line 31, column 3)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>* = nullptr>
stan::promote_args_t<T0__, T1__>
f_a_b(const T0__& a, const T1__& b, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>*>
stan::promote_args_t<T0__, T1__>
f_a_b(const T0__& a, const T1__& b, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 71;
    return ((a * b) / ((a * b) + ((1 - a) * (1 - b))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_HBomics_pal final : public model_base_crtp<model_HBomics_pal> {
private:
  int T;
  int C;
  int S;
  std::vector<int> segment_id;
  std::vector<int> subclone_id;
  std::vector<int> n;
  std::vector<int> A;
  std::vector<int> N;
  std::vector<double> b;
  std::vector<double> v_t;
  std::vector<double> v_j;
  double lambda;
  double mu0;
  double sigma0;
  double s;
  int c;
public:
  ~model_HBomics_pal() {}
  model_HBomics_pal(stan::io::var_context& context__, unsigned int
                    random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_HBomics_pal_namespace::model_HBomics_pal";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 38;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 38;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "C", "int",
        std::vector<size_t>{});
      C = std::numeric_limits<int>::min();
      current_statement__ = 39;
      C = context__.vals_i("C")[(1 - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "C", C, 1);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "S", "int",
        std::vector<size_t>{});
      S = std::numeric_limits<int>::min();
      current_statement__ = 40;
      S = context__.vals_i("S")[(1 - 1)];
      current_statement__ = 40;
      stan::math::check_greater_or_equal(function__, "S", S, 1);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("segment_id", "T", T);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "segment_id", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      segment_id = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 42;
      segment_id = context__.vals_i("segment_id");
      current_statement__ = 42;
      stan::math::check_greater_or_equal(function__, "segment_id",
        segment_id, 1);
      current_statement__ = 42;
      stan::math::check_less_or_equal(function__, "segment_id", segment_id, S);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("subclone_id", "S", S);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "subclone_id", "int",
        std::vector<size_t>{static_cast<size_t>(S)});
      subclone_id = std::vector<int>(S, std::numeric_limits<int>::min());
      current_statement__ = 44;
      subclone_id = context__.vals_i("subclone_id");
      current_statement__ = 44;
      stan::math::check_greater_or_equal(function__, "subclone_id",
        subclone_id, 1);
      current_statement__ = 44;
      stan::math::check_less_or_equal(function__, "subclone_id", subclone_id,
        C);
      current_statement__ = 45;
      stan::math::validate_non_negative_index("n", "S", S);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{static_cast<size_t>(S)});
      n = std::vector<int>(S, std::numeric_limits<int>::min());
      current_statement__ = 46;
      n = context__.vals_i("n");
      current_statement__ = 47;
      stan::math::validate_non_negative_index("A", "T", T);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "A", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      A = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 48;
      A = context__.vals_i("A");
      current_statement__ = 49;
      stan::math::validate_non_negative_index("N", "T", T);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      N = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 50;
      N = context__.vals_i("N");
      current_statement__ = 51;
      stan::math::validate_non_negative_index("b", "T", T);
      current_statement__ = 52;
      context__.validate_dims("data initialization", "b", "double",
        std::vector<size_t>{static_cast<size_t>(T)});
      b = std::vector<double>(T, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 52;
      b = context__.vals_r("b");
      current_statement__ = 52;
      stan::math::check_greater_or_equal(function__, "b", b, 0);
      current_statement__ = 52;
      stan::math::check_less_or_equal(function__, "b", b, 1);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("v_t", "C", C);
      current_statement__ = 54;
      context__.validate_dims("data initialization", "v_t", "double",
        std::vector<size_t>{static_cast<size_t>(C)});
      v_t = std::vector<double>(C, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 54;
      v_t = context__.vals_r("v_t");
      current_statement__ = 54;
      stan::math::check_greater_or_equal(function__, "v_t", v_t, 0);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("v_j", "S", S);
      current_statement__ = 56;
      context__.validate_dims("data initialization", "v_j", "double",
        std::vector<size_t>{static_cast<size_t>(S)});
      v_j = std::vector<double>(S, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 56;
      v_j = context__.vals_r("v_j");
      current_statement__ = 56;
      stan::math::check_greater_or_equal(function__, "v_j", v_j, 0);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "lambda", "double",
        std::vector<size_t>{});
      lambda = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 57;
      lambda = context__.vals_r("lambda")[(1 - 1)];
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "lambda", lambda, 0);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "mu0", "double",
        std::vector<size_t>{});
      mu0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 58;
      mu0 = context__.vals_r("mu0")[(1 - 1)];
      current_statement__ = 58;
      stan::math::check_greater_or_equal(function__, "mu0", mu0, 0);
      current_statement__ = 58;
      stan::math::check_less_or_equal(function__, "mu0", mu0, 1);
      current_statement__ = 59;
      context__.validate_dims("data initialization", "sigma0", "double",
        std::vector<size_t>{});
      sigma0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 59;
      sigma0 = context__.vals_r("sigma0")[(1 - 1)];
      current_statement__ = 59;
      stan::math::check_greater_or_equal(function__, "sigma0", sigma0, 0);
      current_statement__ = 60;
      context__.validate_dims("data initialization", "s", "double",
        std::vector<size_t>{});
      s = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 60;
      s = context__.vals_r("s")[(1 - 1)];
      current_statement__ = 60;
      stan::math::check_greater_or_equal(function__, "s", s, 0);
      current_statement__ = 61;
      context__.validate_dims("data initialization", "c", "int",
        std::vector<size_t>{});
      c = std::numeric_limits<int>::min();
      current_statement__ = 61;
      c = context__.vals_i("c")[(1 - 1)];
      current_statement__ = 61;
      stan::math::check_greater_or_equal(function__, "c", c, 0);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("a", "T", T);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("u", "T", T);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("v", "T", T);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("mu", "T", T);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("theta", "T", T);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("log_lik", "T", T);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("theta_rep", "T", T);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("overdispersion", "T", T);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("var_theta", "T", T);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = T + T + T + T;
  }
  inline std::string model_name() const final {
    return "model_HBomics_pal";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_HBomics_pal_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> a =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 1;
      a = in__.template read_constrain_lub<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1e-5, (1 -
            1e-5), lp__, T);
      Eigen::Matrix<local_scalar_t__,-1,1> u =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 2;
      u = in__.template read_constrain_lub<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1e-5, (1 -
            1e-5), lp__, T);
      Eigen::Matrix<local_scalar_t__,-1,1> v =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 3;
      v = in__.template read_constrain_lub<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1e-5, (1 -
            1e-5), lp__, T);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 4;
      mu = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1e-5, (1 -
             1e-5), lp__, T);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 12;
      for (int id = 1; id <= T; ++id) {
        current_statement__ = 10;
        stan::model::assign(theta,
          f_a_b(stan::model::rvalue(a, "a", stan::model::index_uni(id)),
            stan::model::rvalue(b, "b", stan::model::index_uni(id)),
            pstream__), "assigning variable theta",
          stan::model::index_uni(id));
      }
      current_statement__ = 5;
      stan::math::check_greater_or_equal(function__, "theta", theta, 0);
      current_statement__ = 5;
      stan::math::check_less_or_equal(function__, "theta", theta, 1);
      {
        current_statement__ = 21;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu, mu0, sigma0));
        current_statement__ = 22;
        stan::math::validate_non_negative_index("w", "S", S);
        Eigen::Matrix<local_scalar_t__,-1,1> w =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
        current_statement__ = 24;
        stan::math::validate_non_negative_index("alpha_r", "S", S);
        Eigen::Matrix<local_scalar_t__,-1,1> alpha_r =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
        current_statement__ = 30;
        for (int ids = 1; ids <= S; ++ids) {
          int sc_idx = std::numeric_limits<int>::min();
          current_statement__ = 26;
          sc_idx = stan::model::rvalue(subclone_id, "subclone_id",
                     stan::model::index_uni(ids));
          current_statement__ = 27;
          stan::model::assign(w,
            stan::math::inv_logit((s *
              (stan::model::rvalue(n, "n", stan::model::index_uni(ids)) - c))),
            "assigning variable w", stan::model::index_uni(ids));
          current_statement__ = 28;
          stan::model::assign(alpha_r,
            ((stan::model::rvalue(w, "w", stan::model::index_uni(ids)) *
            stan::model::rvalue(v_j, "v_j", stan::model::index_uni(ids))) +
            ((1 - stan::model::rvalue(w, "w", stan::model::index_uni(ids))) *
            stan::model::rvalue(v_t, "v_t", stan::model::index_uni(sc_idx)))),
            "assigning variable alpha_r", stan::model::index_uni(ids));
        }
        current_statement__ = 37;
        for (int i = 1; i <= T; ++i) {
          int sg_idx = std::numeric_limits<int>::min();
          current_statement__ = 31;
          sg_idx = stan::model::rvalue(segment_id, "segment_id",
                     stan::model::index_uni(i));
          current_statement__ = 32;
          lp_accum__.add(stan::math::beta_lpdf<propto__>(
                           stan::model::rvalue(u, "u",
                             stan::model::index_uni(i)),
                           (stan::model::rvalue(mu, "mu",
                              stan::model::index_uni(i)) *
                           stan::model::rvalue(v_t, "v_t",
                             stan::model::index_uni(
                               stan::model::rvalue(subclone_id,
                                 "subclone_id",
                                 stan::model::index_uni(sg_idx))))), ((1 -
                           stan::model::rvalue(mu, "mu",
                             stan::model::index_uni(i))) *
                           stan::model::rvalue(v_t, "v_t",
                             stan::model::index_uni(
                               stan::model::rvalue(subclone_id,
                                 "subclone_id",
                                 stan::model::index_uni(sg_idx)))))));
          current_statement__ = 33;
          lp_accum__.add(stan::math::gamma_lpdf<propto__>(
                           stan::model::rvalue(v, "v",
                             stan::model::index_uni(i)),
                           (stan::model::rvalue(alpha_r, "alpha_r",
                              stan::model::index_uni(sg_idx)) + 1e-10),
                           lambda));
          current_statement__ = 34;
          lp_accum__.add(stan::math::beta_lpdf<propto__>(
                           stan::model::rvalue(theta, "theta",
                             stan::model::index_uni(i)),
                           (stan::model::rvalue(u, "u",
                              stan::model::index_uni(i)) *
                           stan::model::rvalue(v, "v",
                             stan::model::index_uni(i))), ((1 -
                           stan::model::rvalue(u, "u",
                             stan::model::index_uni(i))) *
                           stan::model::rvalue(v, "v",
                             stan::model::index_uni(i)))));
          current_statement__ = 35;
          lp_accum__.add(stan::math::binomial_lpmf<propto__>(
                           stan::model::rvalue(A, "A",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(N, "N",
                             stan::model::index_uni(i)),
                           stan::model::rvalue(theta, "theta",
                             stan::model::index_uni(i))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_HBomics_pal_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> a =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      a = in__.template read_constrain_lub<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1e-5, (1 -
            1e-5), lp__, T);
      Eigen::Matrix<double,-1,1> u =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      u = in__.template read_constrain_lub<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1e-5, (1 -
            1e-5), lp__, T);
      Eigen::Matrix<double,-1,1> v =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      v = in__.template read_constrain_lub<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1e-5, (1 -
            1e-5), lp__, T);
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      mu = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(1e-5, (1 -
             1e-5), lp__, T);
      Eigen::Matrix<double,-1,1> theta =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(a);
      out__.write(u);
      out__.write(v);
      out__.write(mu);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 12;
      for (int id = 1; id <= T; ++id) {
        current_statement__ = 10;
        stan::model::assign(theta,
          f_a_b(stan::model::rvalue(a, "a", stan::model::index_uni(id)),
            stan::model::rvalue(b, "b", stan::model::index_uni(id)),
            pstream__), "assigning variable theta",
          stan::model::index_uni(id));
      }
      current_statement__ = 5;
      stan::math::check_greater_or_equal(function__, "theta", theta, 0);
      current_statement__ = 5;
      stan::math::check_less_or_equal(function__, "theta", theta, 1);
      if (emit_transformed_parameters__) {
        out__.write(theta);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> theta_rep =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> overdispersion =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> var_theta =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 20;
      for (int id = 1; id <= T; ++id) {
        double alpha_theta = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 13;
        alpha_theta = (stan::model::rvalue(u, "u", stan::model::index_uni(id))
          * stan::model::rvalue(v, "v", stan::model::index_uni(id)));
        double beta_theta = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 14;
        beta_theta = ((1 -
          stan::model::rvalue(u, "u", stan::model::index_uni(id))) *
          stan::model::rvalue(v, "v", stan::model::index_uni(id)));
        current_statement__ = 15;
        stan::model::assign(theta_rep,
          stan::math::beta_rng(alpha_theta, beta_theta, base_rng__),
          "assigning variable theta_rep", stan::model::index_uni(id));
        current_statement__ = 16;
        stan::model::assign(overdispersion, (1 / (1 +
          stan::model::rvalue(v, "v", stan::model::index_uni(id)))),
          "assigning variable overdispersion", stan::model::index_uni(id));
        current_statement__ = 17;
        stan::model::assign(var_theta, ((alpha_theta * beta_theta) /
          (stan::math::pow((alpha_theta + beta_theta), 2) * ((alpha_theta +
          beta_theta) + 1))), "assigning variable var_theta",
          stan::model::index_uni(id));
        current_statement__ = 18;
        stan::model::assign(log_lik,
          stan::math::binomial_lpmf<false>(
            stan::model::rvalue(A, "A", stan::model::index_uni(id)),
            stan::model::rvalue(N, "N", stan::model::index_uni(id)),
            stan::model::rvalue(theta, "theta", stan::model::index_uni(id))),
          "assigning variable log_lik", stan::model::index_uni(id));
      }
      out__.write(log_lik);
      out__.write(theta_rep);
      out__.write(overdispersion);
      out__.write(var_theta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> a =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(a,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(T),
        "assigning variable a");
      out__.write_free_lub(1e-5, (1 - 1e-5), a);
      Eigen::Matrix<local_scalar_t__,-1,1> u =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(u,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(T),
        "assigning variable u");
      out__.write_free_lub(1e-5, (1 - 1e-5), u);
      Eigen::Matrix<local_scalar_t__,-1,1> v =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(v,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(T),
        "assigning variable v");
      out__.write_free_lub(1e-5, (1 - 1e-5), v);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(mu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(T),
        "assigning variable mu");
      out__.write_free_lub(1e-5, (1 - 1e-5), mu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "a", "double",
        std::vector<size_t>{static_cast<size_t>(T)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "u", "double",
        std::vector<size_t>{static_cast<size_t>(T)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "v", "double",
        std::vector<size_t>{static_cast<size_t>(T)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{static_cast<size_t>(T)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> a =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> a_flat__;
        current_statement__ = 1;
        a_flat__ = context__.vals_r("a");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(a, a_flat__[(pos__ - 1)],
            "assigning variable a", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lub(1e-5, (1 - 1e-5), a);
      Eigen::Matrix<local_scalar_t__,-1,1> u =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> u_flat__;
        current_statement__ = 2;
        u_flat__ = context__.vals_r("u");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(u, u_flat__[(pos__ - 1)],
            "assigning variable u", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lub(1e-5, (1 - 1e-5), u);
      Eigen::Matrix<local_scalar_t__,-1,1> v =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> v_flat__;
        current_statement__ = 3;
        v_flat__ = context__.vals_r("v");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(v, v_flat__[(pos__ - 1)],
            "assigning variable v", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lub(1e-5, (1 - 1e-5), v);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_flat__;
        current_statement__ = 4;
        mu_flat__ = context__.vals_r("mu");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(mu, mu_flat__[(pos__ - 1)],
            "assigning variable mu", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lub(1e-5, (1 - 1e-5), mu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"a", "u", "v", "mu"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"theta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string>
        temp{"log_lik", "theta_rep", "overdispersion", "var_theta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(T)},
                std::vector<size_t>{static_cast<size_t>(T)},
                std::vector<size_t>{static_cast<size_t>(T)},
                std::vector<size_t>{static_cast<size_t>(T)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(T)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(T)},
             std::vector<size_t>{static_cast<size_t>(T)},
             std::vector<size_t>{static_cast<size_t>(T)},
             std::vector<size_t>{static_cast<size_t>(T)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      param_names__.emplace_back(std::string() + "a" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      param_names__.emplace_back(std::string() + "u" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      param_names__.emplace_back(std::string() + "v" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta_rep" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "overdispersion" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "var_theta" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      param_names__.emplace_back(std::string() + "a" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      param_names__.emplace_back(std::string() + "u" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      param_names__.emplace_back(std::string() + "v" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "theta_rep" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "overdispersion" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "var_theta" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"a\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"u\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"v\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"theta_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"overdispersion\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"var_theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"a\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"u\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"v\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"theta_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"overdispersion\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"var_theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((T + T) + T) + T);
    const size_t num_transformed = emit_transformed_parameters * (T);
    const size_t num_gen_quantities = emit_generated_quantities * ((((T + T)
      + T) + T));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((T + T) + T) + T);
    const size_t num_transformed = emit_transformed_parameters * (T);
    const size_t num_gen_quantities = emit_generated_quantities * ((((T + T)
      + T) + T));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_HBomics_pal_namespace::model_HBomics_pal;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_HBomics_pal_namespace::profiles__;
}
#endif
#endif
